server:
  port: 8081

spring:
  application:
    name: userservice

management:
  endpoints:
    web:
      exposure:
        include: health,info

# Any custom configs for this service
user:
  default-role: CUSTOMER